joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint effort controllers
joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint1
joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint2
joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint3
joint4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint4
joint5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint5
joint6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: $(arg robot_name)_joint6

# Joint effort trajectory
effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg robot_name)_joint1
    - $(arg robot_name)_joint2
    - $(arg robot_name)_joint3
    - $(arg robot_name)_joint4
    - $(arg robot_name)_joint5
    - $(arg robot_name)_joint6
  gains:
    $(arg robot_name)_joint1: { p: 600, d: 30, i: 0 }
    $(arg robot_name)_joint2: { p: 600, d: 30, i: 0 }
    $(arg robot_name)_joint3: { p: 600, d: 30, i: 0 }
    $(arg robot_name)_joint4: { p: 600, d: 30, i: 0 }
    $(arg robot_name)_joint5: { p: 600, d: 30, i: 0 }
    $(arg robot_name)_joint6: { p: 600, d: 30, i: 0 }
  constraints:
    goal_time: 0.5
    $(arg robot_name)_joint1: { goal: 0.05 }
    $(arg robot_name)_joint2: { goal: 0.05 }
    $(arg robot_name)_joint3: { goal: 0.05 }
    $(arg robot_name)_joint4: { goal: 0.05 }
    $(arg robot_name)_joint5: { goal: 0.05 }
    $(arg robot_name)_joint6: { goal: 0.05 }
