joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint effort controllers
panda_arm_joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: stick_joint1
panda_arm_joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: stick_joint2

# Joint effort trajectory
effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - stick_joint1
    - stick_joint2
  gains:
    stick_joint1: { p: 600, d: 30, i: 0 }
    stick_joint2: { p: 600, d: 30, i: 0 }
  constraints:
    goal_time: 0.5
    stick_joint1: { goal: 0.05 }
    stick_joint2: { goal: 0.05 }
